spring:
  application:
    name: producer-application
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual_immediate
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer

server:
  port: 8085

kafka:
  poc-events:
    topic-name:
      poc.events.in